# Generated by Django 3.2 on 2022-07-28 00:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220727_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_detail', models.TextField(max_length=1000)),
                ('withdraw_type', models.CharField(choices=[('btc', 'Bitcoin'), ('bank', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('p', 'pending'), ('s', 'success'), ('f', 'failed')], default='p', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_address', models.CharField(max_length=1000)),
                ('transaction_hash', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('p', 'pending'), ('s', 'success'), ('f', 'failed')], default='p', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('profit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
