# Generated by Django 3.2 on 2022-07-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220728_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='ammount',
            new_name='amount',
        ),
    ]
