# Generated by Django 3.2 on 2022-07-28 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_ammount_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='date_approved',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='date_approved',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
