# Generated by Django 3.2 on 2022-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220728_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
