# Generated by Django 3.2 on 2023-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_accountmanager_managerrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerrequests',
            name='decription',
            field=models.CharField(default='hello', max_length=1000),
            preserve_default=False,
        ),
    ]
