# Generated by Django 3.2 on 2023-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_decription_managerrequests_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trading_progress',
            field=models.IntegerField(default=0),
        ),
    ]
