# Generated by Django 3.2 on 2023-06-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tradinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.CharField(choices=[('starter', 'Starter'), ('premium', 'Premium'), ('pro', 'Pro')], default='starter', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
