# Generated by Django 3.2 on 2023-06-14 22:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230614_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='btc_balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='eth_balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='shiba_balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12),
        ),
    ]
