# Generated by Django 3.2 on 2023-06-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.CharField(choices=[('starter', 'Starter'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinium', 'Platinium'), ('diamond', 'Diamond'), ('corporate', 'Corprate')], default='starter', max_length=15),
        ),
    ]
