# Generated by Django 3.2 on 2023-06-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_type',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt-trc', 'USDT(TRC20)'), ('usdt-erc', 'USDT(ERC20)'), ('bank', 'Bank Transfer')], max_length=20),
        ),
    ]
