# Generated by Django 3.2 on 2023-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_managerrequests_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerrequests',
            name='full_name',
        ),
        migrations.AddField(
            model_name='accountmanager',
            name='full_name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
