# Generated by Django 3.2 on 2023-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230618_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='role',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
