# Generated by Django 3.2 on 2023-06-20 16:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_accountmanager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('interest', models.IntegerField()),
                ('period', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('leverage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('commission', models.IntegerField()),
            ],
        ),
    ]
