# Generated by Django 3.2 on 2023-06-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_plan_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='leverage',
            field=models.CharField(max_length=10),
        ),
    ]
