# Generated by Django 3.2 on 2023-07-27 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_plan_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trader',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referree', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
