# Generated by Django 3.2 on 2023-07-27 02:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230727_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
