# Generated by Django 3.2 on 2023-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_detailscard_reward_rewarddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarddetails',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
